branches: ["main"]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: >
        sed -i '' 's/^version = ".*"/version = "${nextRelease.version}"/' pyproject.toml
  - - "@semantic-release/git"
    - assets: ["CHANGELOG.md", "pyproject.toml"]
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - - "@semantic-release/exec"
    - successCmd: "/usr/bin/env bash -c 'git push --follow-tags origin main'"
  - "@semantic-release/github"
